language: android
jdk: oraclejdk8

android:
  components:
    - android-21
    - android-25
    - build-tools-25.0.2
  licenses:
      - 'android-sdk-preview-license-.+'
      - 'android-sdk-license-.+'
      - 'google-gdk-license-.+'