language: android
jdk: oraclejdk8

android:
  components:
    - android-21
    - android-24
    - build-tools-24.4.1
    - extra-google-m2repository
    - tools
  licenses:
      - 'android-sdk-preview-license-.+'
      - 'android-sdk-license-.+'
      - 'google-gdk-license-.+'